const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
const PRODUCTS_REQUEST_SUCCESS = "PRODUCTS_REQUEST_SUCCESS";
const PRODUCTS_REQUEST_FAIL = "PRODUCTS_REQUEST_FAIL";

const CATEGORIES_REQUEST = "CATEGORIES_REQUEST";
const CATEGORIES_REQUEST_SUCCESS = "CATEGORIES_REQUEST_SUCCESS";
const CATEGORIES_REQUEST_FAIL = "CATEGORIES_REQUEST_FAIL";

const CATEGORY_FILTER_ADD = "CATEGORY_FILTER_ADD";
const CATEGORY_FILTER_REMOVE = "CATEGORY_FILTER_REMOVE";
const CATEGORY_FILTER_RESET = "CATEGORY_FILTER_RESET";

const SET_SEARCH = "SET_SEARCH";
const CLEAR_SEARCH = "CLEAR_SEARCH";

export {
  PRODUCTS_REQUEST,
  PRODUCTS_REQUEST_SUCCESS,
  PRODUCTS_REQUEST_FAIL,
  CATEGORIES_REQUEST,
  CATEGORIES_REQUEST_SUCCESS,
  CATEGORIES_REQUEST_FAIL,
  CATEGORY_FILTER_ADD,
  CATEGORY_FILTER_REMOVE,
  SET_SEARCH,
  CLEAR_SEARCH,
  CATEGORY_FILTER_RESET,
};
