const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
const PRODUCTS_REQUEST_SUCCESS = "PRODUCTS_REQUEST_SUCCESS";
const PRODUCTS_REQUEST_FAIL = "PRODUCTS_REQUEST_FAIL";

const CATEGORIES_REQUEST = "CATEGORIES_REQUEST";
const CATEGORIES_REQUEST_SUCCESS = "CATEGORIES_REQUEST_SUCCESS";
const CATEGORIES_REQUEST_FAIL = "CATEGORIES_REQUEST_FAIL";

export {
  PRODUCTS_REQUEST,
  PRODUCTS_REQUEST_SUCCESS,
  PRODUCTS_REQUEST_FAIL,
  CATEGORIES_REQUEST,
  CATEGORIES_REQUEST_SUCCESS,
  CATEGORIES_REQUEST_FAIL,
};
